---
#- name: Octavia file Settings
#  template:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    owner: "{{ item.owner }}"
#    group: "{{ item.group }}"
##    mode: "{{ item.mode }}"
#    backup: true
#  with_items:
#    - { src: 'octavia.conf.j2',dest: '/etc/octavia/octavia.conf',owner: 'octavia',group: 'octavia',mode: '0644' }
#  register: octavia_conf

- name: Octavia file Settings
  template:
    src: "{{ item }}"
    dest: /etc/octavia/octavia.conf
    owner: octavia
    group: octavia
    mode: 0644
    backup: true
  with_items:
  - octavia.conf.j2
  register: octavia_conf
  notify:
    - restart octavia-api
    - restart octavia-housekeeping
    - restart octavia-health-manager
    - restart octavia-worker
