---
- import_tasks: octavia-config-set.yml

- name: octavia Service restart
  service: 
    name: "{{ item }}"
    state: restarted
  with_items: 
    - octavia-worker
    - octavia-housekeeping
    - octavia-api
    - octavia-health-manager
    - apache2
    - memcached
  #when: octavia_conf is changed
