---
- name: Create Octavia Network
  openstack.cloud.network:
    cloud: contrabass-octavia
    cacert: "{{ internal_fqdn_cert }}"
    state: present
    name: "{{ OCTAVIA_NETWORK_NAME }}"
    interface: internal

- name: Create Octavia Network Subnet
  openstack.cloud.subnet:
    cloud: contrabass-octavia
    network_name: "{{ OCTAVIA_NETWORK_NAME }}"
    cacert: "{{ internal_fqdn_cert }}"
    state: present
    name: "{{ OCTAVIA_MGMT_SUBNET_NAME }}"
    cidr: "{{ OCTAVIA_MGMT_SUBNET }}"
    allocation_pool_start: "{{ OCTAVIA_MGMT_SUBNET_START }}"
    allocation_pool_end: "{{ OCTAVIA_MGMT_SUBNET_END }}"
    interface: internal
