---
- name: Copy configuration files
  template:
    src: "haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  register: haproxy_conf
  notify:
  - restart haproxy
