---
- import_tasks: check-vip.yml

- include_tasks: check-vip.yml
  when: ("100% packet loss" in external_vip_check.stdout) or ("100% packet loss" in internal_vip_check.stdout)

- include_tasks: haproxy-install.yml
  when: ("100% packet loss" in external_vip_check.stdout) or ("100% packet loss" in internal_vip_check.stdout)

- include_tasks: haproxy-config.yml

- include_tasks: haproxy-pcs-allhost.yml
  when: ("100% packet loss" in external_vip_check.stdout) or ("100% packet loss" in internal_vip_check.stdout)

- include_tasks: haproxy-pcs-mainhost.yml
  when: 
    - inventory_hostname in groups["controller"][0]
    - ("100% packet loss" in external_vip_check.stdout) or ("100% packet loss" in internal_vip_check.stdout)

- include_tasks: haproxy-all-restart.yml
  when: ("100% packet loss" in external_vip_check.stdout) or ("100% packet loss" in internal_vip_check.stdout)
