---
    - name: Create cinder DB
      mysql_db:
        name: "{{ item.db }}"
        state: present
      with_items:
         - db: cinder 

    - name: Update mysql cinder password for all cinder accounts
      no_log: true
      mysql_user:
         name: cinder
         host: "{{ item }}"
         password: "{{ db_password }}"
         priv: cinder.*:ALL,GRANT
         state: present
      with_items:
         - localhost
         - '%'
