---
- include_tasks: cinder-install.yml

- include_tasks: cinder-config-set.yml

- include_tasks: cinder-lvm-set.yml  
  when: enable_cinder_backend_lvm == true

- include_tasks: cinder-database-create.yml
  when: inventory_hostname in groups["controller"][0]

- include_tasks: cinder-dbsync.yml
  when: inventory_hostname in groups["controller"][0]

- include_tasks: cinder-init.yml
  when: inventory_hostname in groups["controller"][0]

- include_tasks: cinder-restart.yml 
