---
- name: Barbican file Settings
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: true
  with_items:
    - { src: 'barbican.conf.j2',dest: '/etc/barbican/barbican.conf',owner: 'barbican',group: 'barbican',mode: '0644' }
  register: barbican_conf
