- name: Copy CSAP files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    directory_mode:
  with_items:
    - { src: 'contrabass-sec',dest: '/root/',owner: 'root',group: 'root',mode: 'preserve' }
    - { src: 'htkim_os_security_08_17',dest: '/root/',owner: 'root',group: 'root',mode: 'preserve' }

- name: Copy CSAP excute shell files all nodes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'os_excute.sh.j2',dest: "/{{ ansible_user }}/os_excute.sh",owner: 'root',group: 'root',mode: '0755' }
  ignore_errors: true

- name: Copy CSAP excute shell files controller
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'con_contrabass_excute.sh.j2',dest: "/{{ ansible_user }}/con_contrabass_excute.sh",owner: 'root',group: 'root',mode: '0755' }
  when: inventory_hostname in groups["controller"]
  ignore_errors: true

- name: Copy CSAP excute shell files compute nodes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'com_contrabass_excute.sh.j2',dest: "/{{ ansible_user }}/com_contrabass_excute.sh",owner: 'root',group: 'root',mode: '0755' }
  when: inventory_hostname in groups["compute"]
  ignore_errors: true
