---
    - name: Create manila DB
      mysql_db:
        name: "{{ item.db }}"
        state: present
      with_items:
         - db: manila

    - name: Update mysql manila password for all manila accounts
      no_log: true
      mysql_user:
         name: manila
         host: "{{ item }}"
         password: "{{ db_password }}"
         priv: manila.*:ALL,GRANT
         state: present
      with_items:
         - localhost
         - '%'
