---
- name: rabbitmq default file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: ../templates/rabbitmq-server.j2 , dest: /etc/default/rabbitmq-server }
    - { src: ../templates/rabbitmq.config.j2, dest: /etc/rabbitmq/rabbitmq.config }
  notify:
    restart rabbitmq-server

- name: Rabbitmq restart
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - rabbitmq-server
  ignore_errors: true
