---
- name: neutron Service restart
  service: 
    name: "{{ item }}"
    state: restarted
  with_items: 
    - neutron-server
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-openvswitch-agent
