- name: Cert Dir Create 
  file:
    path: "{{ certificates_dir }}"
    state: directory
    mode: '0755'

- name: HAProxy-copy
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'haproxy-internal.pem',dest: '{{ certificates_dir }}/haproxy-internal.pem',owner: 'root',group: 'root',mode: '0644' }
    - { src: 'haproxy-external.pem',dest: '{{ certificates_dir }}/haproxy-external.pem',owner: 'root',group: 'root',mode: '0644' }
