---
- name: Ensuring ca directory exist
  file:
    path: "{{ certificates_dir }}/ca"
    state: "directory"
    mode: "0770"

- name: Ensuring private root directory exist
  file:
    path: "{{ root_dir }}"
    state: "directory"
    mode: "0770"

- name: Creating root Certificate key
  command: >
    openssl genrsa
    -out "{{ root_dir }}/root.key"
    4096
  args:
    creates: "{{ root_dir }}/root.key"


- name: Creating and sign root Certificate
  command: >
    openssl req
    -x509
    -new -nodes
    -key "{{ root_dir }}/root.key"
    -sha256
    -days 1024
    -out "{{ root_dir }}/root.crt"
    -subj "/C=KR/ST=Seoul/L=Yeouido/OU=contrabass/CN={{ internal_fqdn }}/"
  args:
    creates: "{{ root_dir }}/root.crt"

- name: Creating and sign external root Certificate
  command: >
    openssl req
    -x509
    -new -nodes
    -key "{{ root_dir }}/root.key"
    -sha256
    -days 1024
    -out "{{ root_dir }}/root_ex.crt"
    -subj "/C=KR/ST=Seoul/L=Yeouido/OU=contrabass/CN={{ external_fqdn }}/"
  args:
    creates: "{{ root_dir }}/root_ex.crt"

- name: Setting permissions on root key
  file:
    path: "{{ root_dir }}/root.key"
    mode: "0660"
    state: file

- name: Creating root Certificate file to be included in container trusted ca-certificates
  copy:
    src: "{{ root_dir }}/root.crt"
    dest: "{{ certificates_dir }}/ca/root.crt"
    mode: "0660"

- name: Creating external root Certificate file to be included in container trusted ca-certificates
  copy:
    src: "{{ root_dir }}/root_ex.crt"
    dest: "{{ certificates_dir }}/ca/root_ex.crt"
    mode: "0660"
