---
- name: Stop all instances
  service: name=mysql state=stopped

- name: Configures for my.cnf setting
  template:
    src: percona8-xtradb-cluster.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
