---
#- name: libcurl4 remove package
#  apt: 
#    name:
#       - libcurl4
#    state: absent

#- name: libcurl4 install package
#  apt: 
#    update_cache: yes
#    name:
#       - libcurl4=7.68.0-1ubuntu2.7
#    state: present
#  register: libcurl4 
#

- name: apt remove
  command: apt remove -y libcurl4

- name: install percona-xtradb-cluster-5.7
  apt:
    update_cache: yes
    name:
       - percona-xtradb-cluster-57
       - python3-mysqldb
       - python3-pymysql
    state: present

- name: copy my.cnf file
  ansible.builtin.template:
    src: "my.cnf.j2"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Update mysql root password for all root accounts
  no_log: true
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    host: "{{ item }}"
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ db_password }}"
    check_implicit_admin: yes
    priv: '*.*:ALL,GRANT'
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - "{{ ansible_hostname }}"

#- name: copy my.cnf2 file
#  template:
#    src: "{{ template_files }}"
#    dest: /root/.my.cnf
#    owner: root
#    group: root
#    mode: 0600
#  with_items:
#    ['root_my.cnf.j2']
