---
- name: NTP Service
  template:
    src: "chrony.conf.main.j2" 
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    ['chrony.conf.main.j2']

- name: chrony service restart
  service:
    name: chrony
    state: restarted
