---
- name: Neutron Compute file Settings
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: true
  with_items:
    - { src: 'neutron.conf.j2',dest: '/etc/neutron/neutron.conf',owner: 'neutron',group: 'neutron',mode: '0644' }
    - { src: 'openvswitch_agent.ini.j2',dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini',owner: 'neutron',group: 'neutron',mode: '0644' }
  register: neutron_compute_conf
  notify: restart neutron-openvswitch-agent
