---
- name: Nova Compute file Settings
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: true
  with_items:
    - { src: 'nova.conf.j2',dest: '/etc/nova/nova.conf',owner: 'nova',group: 'nova',mode: '0644' }
    - { src: 'nova-compute.conf.j2',dest: '/etc/nova/nova-compute.conf',owner: 'root',group: 'nova',mode: '0640' }
  register: nova_compute_conf
  notify: restart nova-compute

- name: libvird.conf file backup
  changed_when: no
  shell: mv /etc/libvirt/libvirtd.conf /etc/libvirt/libvirtd.conf.backup
  ignore_errors: yes

- name: libvirtd.conf file Settings
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'libvirtd.conf',dest: '/etc/libvirt/',owner: 'root',group: 'root',mode: '0644' }
