- name: Fernetkey-copy
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'ceph.conf',dest: '/etc/ceph/',owner: 'ceph',group: 'ceph',mode: '0644' }
