---
- name: Create Ceph Keyring
  command: "{{ item }}"
  with_items:
    - ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
    - ceph auth get-or-create client.cinder-backup mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=backups'
    - ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
    
- name: Get Ceph keyring
  shell: "{{ item }}"
  with_items:
    - ceph auth get-or-create client.cinder | tee {{ ceph_dir }}ceph.client.cinder.keyring
    - ceph auth get-or-create client.cinder-backup | tee {{ ceph_dir }}ceph.client.cinder-backup.keyring
    - ceph auth get-or-create client.glance | tee {{ ceph_dir }}ceph.client.glance.keyring


 
