---
- name:  Pulling Ceph Config files
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    flat: true
  with_items:
    - { src: "{{ ceph_config_file }}",dest: roles/ceph/files/ceph.conf }

