---
- name: Copy to compute ceph uuid-secret file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'uuid-secret.txt',dest: '{{ ceph_dir }}',owner: 'root',group: 'root',mode: '0644' }

- name: Copy to compute ceph secret file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'secret.xml',dest: '{{ ceph_dir }}',owner: 'root',group: 'root',mode: '0644' }

- name: Define secret to virsh
  shell: "{{ item }}"
  with_items:
    - virsh secret-define --file {{ ceph_dir }}secret.xml
    - virsh secret-set-value --secret $(cat {{ ceph_dir }}uuid-secret.txt) --base64 $(cat {{ ceph_dir }}client.cinder.key)
