---
# Handlers for RabbitMQ
- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted
  ignore_errors: true

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started
  ignore_errors: true

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped
  ignore_errors: true
