#- name: Checking File pacemaker Auth file
#  stat:
#    path: /var/lib/pcsd/pcs_users.conf
#  register: pacemaker_auth

- name: HA cluster user intigration
  command: pcs host auth {{ haproxy_com_member }} -u hacluster -p {{ haproxy_pwd }}
#  when: not pacemaker_auth.stat.exists

- name: pcs add remote node
  command: pcs cluster node add-remote "{{ item }}"
  with_items:
  - "{{ groups.compute }}"
  register: already_remote
  #failed_when: already_remote.rc == 0
  ignore_errors: true
  #ignore_errors: ("already exists" in  already_remote.stderr) | true
  failed_when: ("already exists" in  already_remote.stderr)
  when: inventory_hostname in groups["controller"][0]

- name: pcs haproxy resource ban
  command: pcs resource ban haproxy "{{ item }}"
  with_items:
  - "{{ groups.compute }}"

- name: pcs resource clean
  command: pcs resource cleanup
