- name: horizon-cert-key-copy
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: '{{ local_external_cert }}',dest: '{{ external_cert }}',owner: 'root',group: 'root',mode: '0644' }
    - { src: '{{ local_external_key }}',dest: '{{ external_key }}',owner: 'root',group: 'root',mode: '0644' }
  when: enable_horizon_tls | bool
