---
    - name: Create nova DB
      mysql_db:
        name: "{{ item.db }}"
        state: present
      with_items:
         - db: nova
         - db: nova_api
         - db: nova_cell0


    - name: Update mysql nova-api password for all nova-api accounts
      no_log: true
      mysql_user:
         name: nova
         host: "{{ item.host }}"
         password: "{{ db_password }}"
         priv: '{{ item.db }}.*:ALL'
         state: present
         append_privs: yes
      with_items:
         - db: nova
           host: localhost
         - db: nova
           host: '%'
         - db: nova_api
           host: localhost
         - db: nova_api
           host: '%'
         - db: nova_cell0
           host: localhost
         - db: nova_cell0
           host: '%'
